name = "hydra-track-rewards"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "hydraxrd.com/track/*"
zone_name = "hydraxrd.com"

[[routes]]
pattern = "www.hydraxrd.com/track/*"
zone_name = "hydraxrd.com"

[[routes]]
pattern = "hydraxrd.com/track"
zone_name = "hydraxrd.com"

[[routes]]
pattern = "www.hydraxrd.com/track"
zone_name = "hydraxrd.com"

[vars]
SUPABASE_PROJECT_ID = "sljqhrvykycieimacpbe"
SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsanFocnZ5a3ljaWVpbWFjcGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NzMyNjQsImV4cCI6MjA4NjI0OTI2NH0.kq7vjKF_psFItmrB_3dkhtQZUtnrSww1GjSbFwv_j9o"
SUPABASE_URL = "https://sljqhrvykycieimacpbe.supabase.co"
VITE_SUPABASE_PROJECT_ID = "sljqhrvykycieimacpbe"
VITE_SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsanFocnZ5a3ljaWVpbWFjcGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NzMyNjQsImV4cCI6MjA4NjI0OTI2NH0.kq7vjKF_psFItmrB_3dkhtQZUtnrSww1GjSbFwv_j9o"
VITE_SUPABASE_URL = "https://sljqhrvykycieimacpbe.supabase.co"